    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add vessels.json
        git commit -m "Update vessel position" || exit 0
        git push
